primary_date_format:
  weekday: 'short'
secondary_date_format:
  day: 'numeric'
  month: 'short'
time_format:
  hour: '2-digit'
  minute: '2-digit'
  hour12: false
all_day: row
event_variables:
  icon-opacity:
    name: Icon Opacity
    description: The opacity of the event icon (0.0 to 1.0).
  color:
    name: Event Color
    description: The color of the event.
  opacity:
    name: Opacity
    description: The opacity of the event background (0.1 to 1.0).
blank_event:
  icon: mdi:checkbox-blank-circle-outline
  icon-opacity: 0.3
  opacity: 0
blank_all_day_event:
  icon: mdi:checkbox-blank-circle
css: |
  .event-block {
    border-radius: 4px;
  }

  .event-icon {
    color: var(--color, var(--primary-text-color));
    opacity: var(--icon-opacity, 1.0);
  }

  .event-sub-block {
    background-color: rgb(from var(--color, var(--primary-text-color)) r g b / var(--opacity, 0.2));
  }
