primary_date_format:
  weekday: 'short'
secondary_date_format:
  day: 'numeric'
  month: 'short'
time_format:
  hour: '2-digit'
  minute: '2-digit'
  hour12: false
blank_icon: mdi:checkbox-blank-circle-outline
all_day_icon: mdi:checkbox-blank-circle
all_day: row
entities_variables:
  color:
    name: Event Color
    description: The color of the event.
  opacity:
    name: Opacity
    description: The opacity of the event background (0.1 to 1.0).
  border-radius:
    name: Border Radius
    description: The border radius of the event in pixels.
css: |
  [data-type="blank"] {
    &.event-icon {
      opacity: 0.3;
    }
    .event-block {
      opacity: 0.3;
    }
    .event-sub-block {
      opacity: 0.1;
    }
  }

  .event-block {
    border-radius: var(--border-radius, 4px);
  }

  .event-icon {
    color: var(--color, var(--primary-text-color));
  }

  .event-sub-block {
    background-color: rgb(from var(--color, var(--primary-text-color)) r g b / var(--opacity, 0.2));
  }

  [data-type="blank"] .event-sub-block {
    background-color: transparent;
  }
