type: custom:calendar-week-grid-card
primary_date_format:
  weekday: 'short'
secondary_date_format:
  day: 'numeric'
time_format:
  hour: '2-digit'
  minute: '2-digit'
  hour12: false
time_range: false
icons_mode: all
icons_container: event
all_day: row
theme_variables:
  color:
    name: Event Color
    description: The color of the event.
theme_values_examples:
  - color: '#F3511E'
  - color: '#4285F4'
  - color: '#D40101'
  - color: '#34B779'
  - color: '#F6BE28'
event:
blank_event:
  theme_values:
    color: transparent
blank_all_day_event:
entities:
  - name: planned_outages
    entity: calendar.planned_outages
    filter: Outage
    icon: mdi:flash-off
    theme_values:
      color: '#F3511E'
  - name: probable_outages
    entity: calendar.probable_outages
    icon: mdi:flash-off
    theme_values:
      color: '#4285F4'
  - name: emergency_shutdowns
    entity: calendar.planned_outages
    filter: Emergency Shutdowns
    icon: mdi:transmission-tower-off
    theme_values:
      color: '#D40101'
  - name: schedule_applies
    entity: calendar.planned_outages
    filter: Schedule Applies
    icon: mdi:flash-off
    theme_values:
      color: '#34B779'
  - name: waiting_for_schedule
    entity: calendar.planned_outages
    filter: Waiting for Schedule
    icon: mdi:timer-sand
    theme_values:
      color: '#F6BE28'
    hide:
      - planned_outages
css: |
  ha-card {
    --grid-bg: #FFF;
    --grid-border-color: #dde3ea;
    --grid-primary-text-color: #1f1f1f;
    --grid-secondary-text-color: #444746;
    --grid-event-text-color: #fff;
    --grid-accent-color: #0b57d0;
    --grid-accent-text-color: #fff;
  }

  ha-card.theme-dark {
    --grid-bg: #202124;
    --grid-border-color: #3c4043;
    --grid-primary-text-color: #e3e3e3;
    --grid-secondary-text-color: #c4c7c5;
    --grid-event-text-color: #131314;
    --grid-accent-color: #a8c7fa;
    --grid-accent-text-color: #062e6f;
  }

  ha-card {
    background-color: var(--grid-bg);
    box-shadow: none !important;
    border: none !important;
    border-radius: 16px;
    font-family: 'Google Sans', Roboto, Arial, sans-serif;
  }

  /* Grid Styling */

  .grid-container {
    gap: 0px;
  }

  .time-label-wrapper::after {
    content: '';
    position: absolute;
    bottom: 0;
    right: 0;
    width: 10px;
  }

  .time-label-wrapper + .cell-wrapper,
  .cell-wrapper + .cell-wrapper,
  .time-label-wrapper::after {
    border-bottom: 1px solid var(--grid-border-color);
  }

  .time-label-wrapper + .cell-wrapper,
  .cell-wrapper + .cell-wrapper {
    border-left: 1px solid var(--grid-border-color);
  }

  .cell {
    position: relative;
    top: -3px;
    left: -3px;
    height: 28px;
  }

  .day-header {
    padding-bottom: 16px;
  }

  .day-header.today {
    color: var(--grid-accent-color);
  }

  .day-header-primary {
    text-transform: uppercase;
    font-size: 10px;
    font-weight: 500;
    color: var(--grid-secondary-text-color);
  }

  .day-header-secondary {
    position: relative;
    font-size: 16px;
    font-weight: 400;
    color: var(--grid-primary-text-color);
    display: flex;
    align-items: center;
    justify-content: center;
    margin-top: 8px;
    width: 100%;
  }

  .day-header.today .day-header-secondary {
    color: var(--grid-accent-text-color);
  }

  .day-header.today .day-header-secondary:before {
    content: '';
    position: absolute;
    z-index: -1; 
    width: 100%;
    max-width: 30px;
    aspect-ratio: 1/1;
    border-radius: 50%;
    background-color: var(--grid-accent-color);
  }

  .time-label {
    top: -14px;
    font-size: 10px;
    line-height: 10px;
    color: var(--grid-secondary-text-color);
    padding-right: 20px;
  }

  .event-sub-block {
    padding: 2px;
  }

  .event-sub-block:after {
    content: '';
    display: block;
    width: 100%;
    height: 100%;
    border-radius: 6px;
  }

  /* Icons: Subtle placement */

  .event-icon {
    color: var(--grid-event-text-color);
    --icon-size: 14px;
  }

  .event-wrapper:has(.event-sub-block:not([style*="top: 0%;"][style*="height: 100%;"])) .event-icon-overlay {
    display: none;
  }

  /* Current Time Line */

  .current-time-line {
    background-color: #ea4335;
    height: 2px;
  }
  .current-time-circle {
    background-color: #ea4335;
    width: 8px;
    height: 8px;
    left: -4px;
    top: -3px;
  }

  /* Default Event Styles */

  .event-sub-block:after {
    background-color: var(--color, var(--grid-primary-text-color));
  }
