type: custom:calendar-week-grid-card
primary_date_format:
  weekday: 'short'
secondary_date_format:
  day: 'numeric'
time_format:
  hour: '2-digit'
  minute: '2-digit'
  hour12: false
time_range: true
icons_mode: all
icons_container: event
all_day: row
theme_variables:
  color:
    name: Event Color
    description: The color of the event.
theme_values_examples:
  - color: var(--error-color)
  - color: var(--primary-color)
  - color: var(--error-color)
  - color: var(--success-color)
  - color: var(--warning-color)
  - color: var(--info-color)
event:
blank_event:
  theme_values:
    color: transparent
blank_all_day_event:
entities:
  - name: planned_outages
    entity: calendar.planned_outages
    filter: Outage
    icon: mdi:flash-off
    theme_values:
      color: var(--error-color)
  - name: probable_outages
    entity: calendar.probable_outages
    icon: mdi:flash-off
    theme_values:
      color: var(--primary-color)
  - name: emergency_shutdowns
    entity: calendar.planned_outages
    filter: Emergency Shutdowns
    icon: mdi:transmission-tower-off
    theme_values:
      color: var(--error-color)
  - name: schedule_applies
    entity: calendar.planned_outages
    filter: Schedule Applies
    icon: mdi:flash-off
    theme_values:
      color: var(--success-color)
  - name: waiting_for_schedule
    entity: calendar.planned_outages
    filter: Waiting for Schedule
    icon: mdi:timer-sand
    theme_values:
      color: var(--warning-color)
    hide:
      - planned_outages
css: |
  ha-card { 
    --grid-bg: var(--card-background-color, #FFF);
    --grid-border-color: var(--divider-color, #dde3ea);
    --grid-primary-text-color: var(--primary-text-color, #1f1f1f);
    --grid-secondary-text-color: var(--secondary-text-color, #444746);
    --grid-event-text-color: var(--card-background-color, #fff);
    --grid-accent-color: var(--primary-color, #0b57d0);
    --grid-accent-text-color: var(--card-background-color, #fff);
  }

  ha-card.theme-dark {
    --grid-bg: var(--card-background-color, #202124);
    --grid-border-color: var(--divider-color, #3c4043);
    --grid-primary-text-color: var(--primary-text-color, #e3e3e3);
    --grid-secondary-text-color: var(--secondary-text-color, #c4c7c5);
    --grid-event-text-color: var(--card-background-color, #131314);
    --grid-accent-color: var(--primary-color, #a8c7fa);
    --grid-accent-text-color: var(--card-background-color, #062e6f);
  }

  ha-card {
    background-color: var(--grid-bg);
    font-family: 'Google Sans', Roboto, Arial, sans-serif;
  }

  /* Grid Styling */

  .grid-container {
    gap: 0px;
  }

  .time-label-wrapper::after {
    content: '';
    position: absolute;
    bottom: 0;
    right: 0;
    width: 10px;
  }

  .time-label-wrapper + .cell-wrapper,
  .cell-wrapper + .cell-wrapper,
  .time-label-wrapper::after {
    border-bottom: 1px solid var(--grid-border-color);
  }

  .time-label-wrapper + .cell-wrapper,
  .cell-wrapper + .cell-wrapper {
    border-left: 1px solid var(--grid-border-color);
    padding-right: 4px;
    padding-bottom: 4px;
  }

  .cell {
    position: relative;
    top: -1px;
    left: -1px;
    height: 24px;
  }

  .day-header {
    padding-bottom: 16px;
  }

  .day-header.today {
    color: var(--grid-accent-color);
  }

  .day-header-primary {
    text-transform: uppercase;
    font-size: 10px;
    font-weight: 500;
    color: var(--grid-secondary-text-color);
  }

  .day-header-secondary {
    position: relative;
    font-size: 16px;
    font-weight: 400;
    color: var(--grid-primary-text-color);
    display: flex;
    align-items: center;
    justify-content: center;
    margin-top: 8px;
    width: 100%;
  }

  .day-header.today .day-header-secondary {
    color: var(--grid-accent-text-color);
  }

  .day-header.today .day-header-secondary:before {
    content: '';
    position: absolute;
    z-index: -1; 
    width: 100%;
    max-width: 30px;
    aspect-ratio: 1/1;
    border-radius: 50%;
    background-color: var(--grid-accent-color);
  }

  .time-label-wrapper {
    position: relative;
  }

  .time-label {
    display: block;
    position: relative;
    font-size: 10px;
    line-height: 10px;
    color: var(--grid-secondary-text-color);
    padding-right: 0;
    margin-right: 20px;
    text-align: right;
  }

  .time-label-all-day {
    font-size: 8px;
  }

  .time-label-hour-separator {
    display: none;
  }

  .time-label-hour-start,
  .time-label-all-day,
  .time-label-hour-end {
    display: block;
  }

  .time-label-hour:not(.time-label-hour-end), 
  .time-label-all-day {
    position: relative;
    top: -5px;
    right: 0;
  }

  .time-label-hour-end {
    position: absolute;
    right: 0;
    bottom: -5px;
  }

  .time-label-wrapper:has(~ .time-label-wrapper) .time-label-hour-end {
    visibility: hidden;
  }

  .event-block {
    border-radius: 6px;
  }

  /* Icons: Subtle placement */

  .event-icon {
    color: var(--grid-event-text-color);
    --icon-size: 14px;
  }

  /* Current Time Line */

  .current-time-line {
    background-color: var(--warning-color);
    height: 2px;
  }
  .current-time-circle {
    background-color: var(--warning-color);
    width: 8px;
    height: 8px;
    left: -4px;
    top: -3px;
  }

  /* Default Event Styles */

  .event-sub-block {
    background-color: var(--color, var(--grid-primary-text-color));
  }
