type: custom:calendar-week-grid-card
primary_date_format:
  weekday: 'short'
secondary_date_format:
  day: 'numeric'
  month: 'short'
time_format:
  hour: '2-digit'
  minute: '2-digit'
  hour12: false
time_range: false
icons_mode: top
icons_container: cell
all_day: row
theme_variables:
  icon-opacity:
    name: Icon Opacity
    description: The opacity of the event icon (0.0 to 1.0).
  color:
    name: Event Color
    description: The color of the event.
  opacity:
    name: Opacity
    description: The opacity of the event background (0.1 to 1.0).
  border-style:
    name: Border Style
    description: The border style of the event (solid, dashed, dotted, double).
  border-opacity:
    name: Border Opacity
    description: The opacity of the event border (0.0 to 1.0).
theme_values_examples:
  - color: var(--error-color)
    opacity: 0.1
    border-style: solid
  - color: var(--warning-color)
    opacity: 0.1
    border-style: dashed
  - color: var(--error-color)
    opacity: 0.2
    border-style: double
  - color: var(--success-color)
    opacity: 0.1
    border-style: dotted
  - color: var(--info-color)
    opacity: 0.1
    border-style: dotted
blank_event:
  icon: mdi:checkbox-blank-circle-outline
  icon-opacity: 0.3
  opacity: 0
  border-opacity: 0.3
blank_all_day_event:
  icon: mdi:checkbox-blank-circle
entities:
  - name: planned_outages
    entity: calendar.planned_outages
    filter: Outage
    icon: mdi:flash-off
    color: var(--error-color)
    opacity: 0.1
    border-style: solid
  - name: probable_outages
    entity: calendar.probable_outages
    icon: mdi:alert-circle-outline
    color: var(--warning-color)
    opacity: 0.1
    border-style: dashed
  - name: emergency_shutdowns
    entity: calendar.planned_outages
    filter: Emergency Shutdowns
    icon: mdi:transmission-tower-off
    color: var(--error-color)
    opacity: 0.2
    border-style: double
  - name: schedule_applies
    entity: calendar.planned_outages
    filter: Schedule Applies
    icon: mdi:flash-off
    color: var(--success-color)
    opacity: 0.1
    border-style: dotted
  - name: waiting_for_schedule
    entity: calendar.planned_outages
    filter: Waiting for Schedule
    icon: mdi:timer-sand
    color: var(--info-color)
    opacity: 0.1
    border-style: dotted
    hide:
      - planned_outages
css: |
  .event-block {
    border-radius: 4px;
    border: 1px var(--border-style, dotted) rgb(from var(--color, var(--primary-text-color)) r g b / var(--border-opacity, 1.0));
  }

  .event-icon {
    color: var(--color, var(--primary-text-color));
    opacity: var(--icon-opacity, 1.0);
  }

  .event-sub-block {
    background-color: rgb(from var(--color, var(--primary-text-color)) r g b / var(--opacity, 0.1));
  }
