type: custom:calendar-week-grid-card
primary_date_format:
  weekday: 'short'
secondary_date_format:
  day: 'numeric'
  month: 'short'
time_format:
  hour: '2-digit'
  minute: '2-digit'
  hour12: false
time_range: false
icons_container: event
icons_mode: all
all_day: row
theme_variables:
  color:
    name: Event Color
    description: The color of the event icon.
  background:
    name: Background
    description: The background color of the event.
theme_values_examples:
  - color: '#FFFFFF'
    background: '#FF8A80'
  - color: '#1B5E20'
    background: '#B9F6CA'
  - color: '#FFFFFF'
    background: '#FF80AB'
  - color: '#F57F17'
    background: '#FFF176'
  - color: '#006064'
    background: '#80DEEA'
blank_event:
  icon: mdi:circle-outline
  color: '#E0E0E0'
  background: '#F5F5F5'
blank_all_day_event:
  icon: mdi:checkbox-blank-circle
entities:
  - name: planned_outages
    entity: calendar.planned_outages
    filter: Outage
    icon: mdi:close-circle
    color: '#FFFFFF'
    background: '#FF8A80'
  - name: probable_outages
    entity: calendar.probable_outages
    icon: mdi:close-circle
    color: '#1B5E20'
    background: '#B9F6CA'
  - name: emergency_shutdowns
    entity: calendar.planned_outages
    filter: Emergency Shutdowns
    icon: mdi:alert-circle
    color: '#FFFFFF'
    background: '#FF80AB'
  - name: schedule_applies
    entity: calendar.planned_outages
    filter: Schedule Applies
    icon: mdi:circle-outline
    color: '#F57F17'
    background: '#FFF176'
  - name: waiting_for_schedule
    entity: calendar.planned_outages
    filter: Waiting for Schedule
    icon: mdi:clock-outline
    color: '#006064'
    background: '#80DEEA'
    hide:
      - planned_outages
css: |
  ha-card {
    --text-color: #444;
    --text-primary: var(--text-color);
    --text-secondary: var(--text-color);
  }

  ha-card {
    background: #FFFFFF;
    border-radius: 24px;
    box-shadow: 0 8px 16px rgba(0,0,0,0.1);
  }

  .grid-container {
    gap: 8px;
  }

  .cell-wrapper {
    min-height: 28px;
  }

  .cell {
    height:34px;
    border-radius: 17px;
  }

  .event-icon {
    --icon-size: 20px;
    color: var(--color, var(--primary-text-color));
  }

  .event-block {
    background-color: var(--background, #F5F5F5);
  }
