type: custom:calendar-week-grid-card
language: en
time_format: 'HH:mm'
style:
  '--event-border-radius': 4px
  '--main-color': var(--primary-text-color)
cell_blank:
  style:
    border: 1px dotted var(--main-color)
    opacity: 0.3
  icon:
    icon: mdi:checkbox-blank-circle-outline
    style:
      opacity: 0.3
entities:
  - entity: calendar.probable_outages
    cell:
      style:
        border: 1px dashed var(--main-color)
      icon:
        icon: mdi:alert-circle-outline
        style:
          color: var(--main-color)
      background:
        style:
          background-color: var(--main-color)
          opacity: 0.1
  - entity: calendar.planned_outages
    filter: Outage
    cell:
      style:
        border: 1px solid var(--main-color)
      icon:
        icon: mdi:flash-off
        style:
          color: var(--main-color)
      background:
        style:
          background-color: var(--main-color)
          opacity: 0.1
  - entity: calendar.planned_outages
    filter: Emergency Shutdowns
    cell:
      style:
        border: 1px double var(--main-color)
      icon:
        icon: mdi:transmission-tower-off
        style:
          color: var(--main-color)
      background:
        style:
          background-color: var(--main-color)
          opacity: 0.2
  - entity: calendar.planned_outages
    filter: Waiting for Schedule
    cell:
      style:
        border: 1px dotted var(--main-color)
        opacity: 0.4
      icon:
        icon: mdi:timer-sand
        style:
          color: var(--main-color)
  - entity: calendar.planned_outages
    filter: Schedule Applies
    cell:
      style:
        border: 1px groove var(--main-color)
        opacity: 0.4
      icon:
        icon: mdi:calendar-check
        style:
          color: var(--main-color)
